# This file was generated by GoReleaser. DO NOT EDIT.
cask "synth" do
  version "0.0.1-alpha.31"

  on_macos do
    on_intel do
      sha256 "43bd545a82988ae88691bfbca0b5dd786a80ab456f783b4dcab7b3bc2d1bdc65"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "deea7f7af33ad4445c088cfde3fa720f69cea41a6439ea5aa740cbbc0f939b57"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "342453de4048ae95e8661535c1ccc21da0e68228ea9718b1d75ee643a8d5b88c"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_linux_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "b8740324861d8f0738e1e2af10839db59becc88a128658a9fb623242f9ac610c"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_linux_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  name "synth"
  desc "Synth CLI"
  homepage "https://synthlabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synth"

  # No zap stanza required

end
