# This file was generated by GoReleaser. DO NOT EDIT.
cask "synth" do
  version "0.0.1-alpha.39"

  on_macos do
    on_intel do
      sha256 "0d6ceb09cc1f1921cffd9536c4a2cc6df879e469b93a3822c2f4a9f92a6c0117"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "1f2fbb21306f7a1d702dab3bd71690655058c726e60b8b5ebcd1d8dd623bf7b7"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d5e0f8ba6ba47581da7678cecb29711f5565240469571fddadbe0445d7f9ae30"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_linux_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "56d20bcbcc956ac4d8c8a76b3b37cc4a2aa59e42e508887d6d56068945324295"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth_#{version}_linux_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  name "synth"
  desc "Synth CLI"
  homepage "https://synthlabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synth"

  # No zap stanza required

end
