# This file was generated by GoReleaser. DO NOT EDIT.
cask "synth-harbor" do
  version "0.0.1-alpha.2"

  deprecate! date: "2026-07-16",
    because: "has been replaced by the unified synth cask; Harbor commands now live under `synth harbor ...`",
    replacement_cask: "synth"

  on_macos do
    on_intel do
      sha256 "8909f6954e29c922d48b56f795dc4225875592eec40f766e998756d7f81a802f"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "a8e60d85fbe9e5e5835caf942b367010b87da254854f4e5dffc7de83f738c1a4"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6cbd13cb27ee764aa69105949b53be25723325168fe2e7ef5a5298de71e5ab27"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "c54e29d9534e8a1c8598ad922686e84ce3cb09cab48c175ff323ddc005bc7aa6"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  name "synth-harbor"
  desc "synth-harbor - Harbor-compatible CLI backed by Sprite Gateway"
  homepage "https://synthlabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  caveats do
    <<~EOS
      `synth-harbor` is retired in favor of the unified `synth` CLI.

      Migration:
        brew uninstall --cask synth-harbor
        brew install --cask synth

      Command examples:
        synth-harbor auth login        -> synth auth login
        synth-harbor job start         -> synth harbor job start
        synth-harbor adapter review    -> synth harbor adapter review
    EOS
  end

  binary "synth-harbor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synth-harbor"]
    end
  end

  # No zap stanza required

end
