# This file was generated by GoReleaser. DO NOT EDIT.
cask "synth-harbor" do
  version "0.0.1-alpha.1"

  on_macos do
    on_intel do
      sha256 "45e83be0908d9e01209d0801fb072b113eccf32df7b2999e16a094017c518b73"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "dcf80f43dfff1bffa0b56e5ca19995affbe756577469981376c91714340eca51"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca927527d1f35a3846ab52473c59f241eede8e0c6acfc0952dc40dfe603e5db4"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
    on_arm do
      sha256 "437f1fdb1fdeecacd3aefa708a3806b8e40083afcfcd5e877becec21d6bc2167"
      url "https://github.com/SynthLabsAI/synth-releases/releases/download/v#{version}/synth-harbor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/SynthLabsAI/synth-releases/"
    end
  end

  name "synth-harbor"
  desc "synth-harbor - Harbor-compatible CLI backed by Sprite Gateway"
  homepage "https://synthlabs.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synth-harbor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synth-harbor"]
    end
  end

  # No zap stanza required

end
