# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synth < Formula
  desc "synth - synthetic training data at scale"
  homepage "https://synthlabs.ai"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nlile/synth/releases/download/v0.1.0/synth_0.1.0_darwin_amd64.tar.gz"
      sha256 "e167b512d14044ef21a7991e1244519ded474be138a44e1cc07a0d87f62f0428"

      define_method(:install) do
        bin.install "synth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nlile/synth/releases/download/v0.1.0/synth_0.1.0_darwin_arm64.tar.gz"
      sha256 "c154e544ae81b935aa01ae0a55360d121d4b8de61e860459d08402934f4b5724"

      define_method(:install) do
        bin.install "synth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlile/synth/releases/download/v0.1.0/synth_0.1.0_linux_amd64.tar.gz"
      sha256 "639ebe6d2f5814b6ba03fd12237a7eabf493a327c296822520d165fa050a2bbc"
      define_method(:install) do
        bin.install "synth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlile/synth/releases/download/v0.1.0/synth_0.1.0_linux_arm64.tar.gz"
      sha256 "22156373b258a39cd3e9fbae1152ce94bb8bd0329975aa2de84b41e1542689ea"
      define_method(:install) do
        bin.install "synth"
      end
    end
  end

  test do
    system "#{bin}/synth", "--version"
  end
end
