# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synth < Formula
  desc "synth - synthetic training data at scale"
  homepage "https://synthlabs.ai"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nlile/synth/releases/download/v0.1.1/synth_0.1.1_darwin_amd64.tar.gz"
      sha256 "0d33d345d4fbe2e4d4dc2df8bea4fd0f5340d9a46ca85a589ec369024eb5af06"

      define_method(:install) do
        bin.install "synth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nlile/synth/releases/download/v0.1.1/synth_0.1.1_darwin_arm64.tar.gz"
      sha256 "d14a7d59f15c8a601f6e7781ceda67dddf850cd94f8fa0095bb0c6319930e886"

      define_method(:install) do
        bin.install "synth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlile/synth/releases/download/v0.1.1/synth_0.1.1_linux_amd64.tar.gz"
      sha256 "12d0542e0625ce601c3abd9e1cbf702b37ab38d530eb48d185e82755930ab784"
      define_method(:install) do
        bin.install "synth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlile/synth/releases/download/v0.1.1/synth_0.1.1_linux_arm64.tar.gz"
      sha256 "240138494448373ddb6e8663b2b18870049515f48e40ea7413459ea68ba7bfb6"
      define_method(:install) do
        bin.install "synth"
      end
    end
  end

  test do
    system "#{bin}/synth", "--version"
  end
end
